title: Human Modeling Group
description: Yuichi Kurita Group

url: https://humanmodeling.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: humanmodeling
   twitter: mykurita
   facebook: ykurilab
   email: ykurita@hiroshima-u.ac.jp

google_analytics: "UA-58263416-1"
